config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:index, :show]

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end

  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  mount ActionCable.server => '/cable'
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  has_many :technologies, dependent: :destroy
  accepts_nested_attributes_for :technologies,
                                allow_destroy: true,
                                reject_if: lambda { |attrs| attrs['name'].blank? }
  
  include Placeholder

  validates_presence_of :title, :body, :main_image, :thumb_image
  mount_uploader :thumb_image, PortfolioUploader
  mount_uploader :main_image, PortfolioUploader

  def self.angular
    where(subtitle: "Angular")
  end

  def self.by_position
    order("position ASC")
  end

  scope :ruby_on_rails_portfolio_items, -> { where(subtitle: "Ruby on rails") }

  after_initialize :set_defaults

  def set_defaults
    self.main_image ||= Placeholder.image_generator(height: '600', width: '400')
    self.thumb_image ||= Placeholder.image_generator(height: '350', width: '200')
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  skip_before_action :verify_authenticity_token

  before_action :set_portfolio_item, only: [:edit, :update, :show, :destroy]
  layout 'portfolio'
  access all: [:show, :index, :angular], user: { except: [:destroy, :new, :create, :update, :edit, :sort] }, side_admin: :all

  def index
    @portfolio_items = Portfolio.by_position
  end

  def sort
    params[:order].each do |key, value|
      Portfolio.find(value[:id]).update(position: value[:position])
    end

    render body: nil
  end

  def angular
    @angular_portfolio_items = Portfolio.angular
  end

  def new
    @portfolio_item = Portfolio.new
  end

  def create
    @portfolio_item = Portfolio.new(portfolio_params)

    respond_to do |format|
      if @portfolio_item.save
        format.html { redirect_to portfolios_path, notice: 'Portfolio was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @portfolio_item.update(portfolio_params)
        format.html { redirect_to portfolios_path, notice: 'Portfolio was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def show
  end

  def destroy
    @portfolio_item.destroy

    respond_to do |format|
      format.html { redirect_to portfolios_url, notice: 'Portfolio was successfully destroyed.' }
    end
  end

  private

  def portfolio_params
    params.require(:portfolio).permit(:title, 
                                      :subtitle, 
                                      :body,
                                      :thumb_image,
                                      :main_image,
                                      technologies_attributes: [:id, :name, :_destroy]
                                    )
  end

  def set_portfolio_item
    @portfolio_item = Portfolio.find(params[:id])
  end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/portfolios/_form.html.erb
<%= form_for(@portfolio_item) do |form| %>
  <% if @portfolio_item.errors.any? %>
    <% @portfolio_item.errors.full_messages.each do |error| %> 
      <%= alert_generator error %>
    <% end %>
  <% end %>

  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= form.label :title %>
        <%= form.text_field :title, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :subtitle %>
        <%= form.text_field :subtitle, class: "form-control" %>
      </div>

      <div class="form-group">
        <label class="btn btn-primary">
          Upload a main image <%= form.file_field :main_image, style: "display:none;" %>
        </label>
      </div>

      <div class="form-group">
         <label class="btn btn-primary">
          Upload a thumb image <%= form.file_field :thumb_image, style: "display:none;" %>
        </label>
      </div>
    </div>

    <div class="col-md-6">
      <div class="form-group">
        <%= form.label :body %>
        <%= form.text_area :body, class: "form-control", rows: 15 %>
      </div>
    </div>
  </div>

  <div class="col-md-12">
    <h3>Technologies used:</h3>
    <div>
      <%= form.fields_for :technologies do |technology_form|%>
        <%= render 'technology_fields', f: technology_form %>
      <% end %>
    </div>

    <div>
      <%= link_to_add_association "Add technology", form, :technologies %>
    </div>

    <div class="form-group">
      <%= form.submit "Submit", class: "btn btn-primary" %>
    </div>
    <div class="form-group">
      <%= link_to "Back to portfolio page", portfolios_path %>
    </div>
  </div> 
<% end %>

app/views/portfolios/_portfolio_item.html.erb
 <div class="col-md-4">
  <div class="card mb-4 shadow-sm" data-id="<%= portfolio_item.id %>">
    <%= image_tag(portfolio_item.thumb_image_url, class: "card-img-top") unless portfolio_item.thumb_image_url.nil? %>
    
    <div class="card-body">
      <p class="card-text">
        <span><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %></span>
        <%= portfolio_item.subtitle %>
        <%#= portfolio_item.body %>
      </p>
    </div>
  </div>
</div>

app/views/portfolios/_technology_fields.html.erb
<div class="form-group nested-fields">
  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control" %>
  <%= link_to_remove_association "Remove technology", f %>
</div>

app/views/portfolios/angular.html.erb
<h1>angular Portfolio items</h1>

<%= link_to "Create new item", new_portfolio_path if logged_in?(:side_admin)%>

<% @angular_portfolio_items.each do |portfolio_item| %>
  <p><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %></p>
  <p><%= portfolio_item.subtitle %></p>
  <p><%= portfolio_item.body %></p>
  <%= image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil? %>
  
  <% if logged_in?(:side_admin) %> 
    <%= link_to "Edit", edit_portfolio_path(portfolio_item) %>
    <%= link_to 'Delete Portfolio Item', portfolio_path(portfolio_item), 
      method: :delete, data: { confirm: 'Are you sure?' } %>
  <% end %>
<% end %>

app/views/portfolios/edit.html.erb
<div class="container portfolio-container">
  <h1>Edit this portfolio item</h1> 

  <%= render 'form', portfolio_item: @portfolio_item %>
</div>

app/views/portfolios/index.html.erb
 <div class="album py-5 bg-light">
  <div class="container">
    <%= source_helper('alert alert-primary') %>
    <div class="new-portfolio col-12 d-flex justify-content-end align-items-center">
      <%= link_to "Create a new Portfolio", new_portfolio_path if logged_in?(:side_admin) %>
    </div>
    <div class="row <%= "sortable" if logged_in?(:side_admin) %>">
        <%= render partial: 'portfolio_item', collection: @portfolio_items %>
    </div>
  </div>
</div>

app/views/portfolios/new.html.erb
<div class="container portfolio-container">
  <h1>Create a new portfolio item</h1> 

  <%= render 'form', portfolio_item: @portfolio_item %>
</div>

app/views/portfolios/show.html.erb
<div class="container portfolio-container">
  <div class="row">
    <div class="col-md-4">
      <%= image_tag @portfolio_item.main_image_url, width: "100%" %>
      <div class="d-flex justify-content-between align-items-center">
        <div class="btn">
          <% if logged_in?(:side_admin) %>
            <%= link_to "Edit", edit_portfolio_path(@portfolio_item), class: "btn btn-sm btn-outline-secondary" %>
            <%= link_to 'Delete Portfolio Item', portfolio_path(@portfolio_item), 
              method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-outline-secondary" %>
          <% end %>
          <div>
            <%= link_to "Back to portfolio page", portfolios_path %>
          </div>
        </div>
      </div>    
    </div>

    <div class="col-md-8">
      <h1><%= @portfolio_item.title %></h1>
      <hr>
      <em><%= @portfolio_item.subtitle %></em>
      <p><%= markdown @portfolio_item.body %></p>
      <hr>
      <h2>Technologies used:</h2>
      
      <% @portfolio_item.technologies.each do |t| %>
        <span class="badge badge-pill badge-info"><%= t.name %></span>
      <% end %>
    </div>
  </div>
</div>