config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:index, :show]

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end

  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  mount ActionCable.server => '/cable'
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_application_footer.html.erb
<footer class="mastfoot">
  <div class="inner">
    <p><%= copyright_generator %></p>
  </div>
</footer>

app/views/shared/_application_nav.html.erb
<header>
  <div class="nav-header row justify-content-center">
    <div class="brand-name col-8 pt-1">
      <h3 class="masthead-brand">Bianca Velázquez</h3>
    </div>

    <div class="login col-4 d-flex justify-content-end align-items-center">
      <%= login_helper 'btn btn-sm btn-outline-light session' %>
    </div>
  </div>

  <div class="row justify-content-center">
    <nav class="nav nav-masthead justify-content-center app-nav">
      <%= nav_helper "nav-link", "div" %>
    </nav>
  </div>
</header>

app/views/shared/_blog_jumbotron.html.erb
<div class="jumbotron p-3 p-md-5 text-white rounded">
  <div class="col-md-6 px-0">
    <h1 class="display-4 font-italic">Title of a longer featured blog post</h1>
    <p class="lead my-3">Multiple lines of text that form the lede, informing new readers quickly and efficiently about what's most interesting in this post's contents.
    </p>
    <p class="lead mb-0">
      <a href="#" class="text-white font-weight-bold">Continue reading...</a>
    </p>
  </div>
</div>

app/views/shared/_blog_masthead.html.erb
<div class="container border-bottom">
  <div class="row ">
    <div class="col-6 pt-1">
      <h3 class="font-italic ">My Blog</h3>
    </div>
    <div class="col-6 d-flex justify-content-end align-items-center">
      <span><%= link_to 'Write a new blog', new_blog_path if logged_in?(:side_admin) %></span>
    </div>
  </div>
</div>

app/views/shared/_blog_nav.html.erb
<header>
  <div class="nav-header row">
    <div class="brand-name col-8 pt-1">
      <h3 class="masthead-brand">Bianca Velázquez</h3>
    </div>

    <div class="login col-4 d-flex justify-content-end align-items-center">
      <%= login_helper 'btn btn-sm btn-outline-secondary session' %>
    </div>
  </div>

  <div class="row justify-content-center">
    <nav class="nav nav-masthead justify-content-center app-nav">
      <%= nav_helper "nav-link text-muted", "div" %>
    </nav>
  </div>
</header>

app/views/shared/_blog_sidebar.html.erb
<aside class="col-md-4 blog-sidebar">
  <div class="p-3 mb-3 bg-light rounded">
    <h4 class="font-italic">About</h4>
    <p class="mb-0">
      Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.
    </p>
  </div>

  <%= source_helper('alert alert-primary') %>

  <div class="p-3">
    <h4 class="font-italic">Topics</h4>
    <% @set_sidebar_topics.each do |topic| %>
      <div>
        <%= link_to topic.title, topic_path(topic), class: "badge badge-pill badge-info" %>
      </div>
    <% end %>
    <span><%= link_to 'See all topics', topics_path %></span>
  </div>

  <div class="p-3">
    <h4 class="font-italic">Elsewhere</h4>
    <ol class="list-unstyled social-links nav d-flex justify-content-left">
      <li class="p-2 text-muted"><a href="https://github.com "><%= fa_icon "github" %></a></li>
      <li class="p-2 text-muted"><a href="https://www.facebook.com"><%= fa_icon "facebook" %></a></li>
      <li class="p-2 text-muted"><a href="https://www.instagram.com/"><%= fa_icon "instagram" %></a></li>
      <li class="p-2 text-muted"><a href="https://twitter.com/" ><%= fa_icon "twitter" %></a></li>
      <li class="p-2 text-muted"><a href="https://linkedin.com"><%= fa_icon "linkedin" %></a></li>
    </ol>
  </div>
</aside>

app/views/shared/_nav.html.erb
<header class="masthead mb-auto">
  <div class="inner">
    <h3 class="masthead-brand">Bianca Velázquez</h3>     
    <div class="nav-scroller py-1 mb-2">
      <nav class="col-md-6 nav d-flex justify-content-left">
        <%= nav_helper "p-2 text-muted", "div" %>
        <div><%= login_helper 'btn btn-sm btn-outline-light session' %></div>
      </nav>
    </div>
  </div>
</header>

app/views/shared/_portfolio_masthead.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">My Portfolio</h1>
    <p class="lead">
      Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don't simply skip over it entirely.
    </p>  
    <p>
      <%= link_to "Find out more about me", about_me_path, class: "btn btn-sm btn-outline-light" %>
      <%= link_to "My Blog", blogs_path, class: "btn btn-sm btn-outline-light" %>
    </p>
  </div>
</section>

app/views/shared/_portfolio_nav.html.erb
<header>
  <div class="nav-header row">
    <div class="brand-name col-8 pt-1">
      <h3 class="masthead-brand">Bianca Velázquez</h3>
    </div>

    <div class="login col-4 d-flex justify-content-end align-items-center">
      <%= login_helper 'btn btn-sm btn-outline-secondary session' %>
    </div>
  </div>

  <div class="row justify-content-center">
    <nav class="nav nav-masthead justify-content-center app-nav">
      <%= nav_helper "nav-link text-muted", "div" %>
    </nav>
  </div>
</header>
        